CREATE TABLE `MF_ACCOUNT` (
  `ACCOUNT_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `EMAIL` varchar(50) DEFAULT NULL,
  `LOGIN_AUTH_PROVIDER` enum('EMPTY','GOOGLE','KAKAO','NAVER') DEFAULT NULL,
  `LOGIN_AUTH_PROVIDER_ID` varchar(100) NOT NULL,
  `NAME` varchar(100) DEFAULT NULL,
  `PROFILE` varchar(255) DEFAULT NULL,
  `ROLE` enum('ADMIN','USER') NOT NULL,
  `STATUS` enum('FACE_UNIDENTIFIED','NORMAL','WITHDRAWN','SUSPENDED') NOT NULL,
  `CREATED_ACCOUNT_ID` bigint(20) DEFAULT NULL,
  `CREATED_DATE` datetime(6) DEFAULT NULL,
  `MODIFIED_ACCOUNT_ID` bigint(20) DEFAULT NULL,
  `MODIFIED_DATE` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`ACCOUNT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8;

CREATE TABLE `MF_TOKEN` (
  `ACCOUNT_ID` bigint(20) NOT NULL,
  `ACCESS_TOKEN` varchar(255) DEFAULT NULL,
  `REFRESH_TOKEN` varchar(255) DEFAULT NULL,
  `CREATED_ACCOUNT_ID` bigint(20) DEFAULT NULL,
  `CREATED_DATE` datetime(6) DEFAULT NULL,
  `MODIFIED_ACCOUNT_ID` bigint(20) DEFAULT NULL,
  `MODIFIED_DATE` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`ACCOUNT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;